name: cloud_functions_dart_example
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_functions_interop: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.1
